class CfgGroups
{
	class West
	{
		name = $STR_A3_CfgGroups_West0;
		side = TWest;
		class CUP_B_CDF
		{
			name = $STR_A3_CfgGroups_West_BLU_F0;
			class Infantry
			{
				name = $STR_A3_CfgGroups_West_BLU_F_Infantry0;
				class EfC_B_Team01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Soldier_TL_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_AR_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Medic_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_CDF_Team02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Officer_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_AR_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_CDF_Team03
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Soldier_TL_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MG_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Soldier_LAT_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_CDF_Team04
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Officer_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MG_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Soldier_RPG18_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_CDF_Team05
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Soldier_TL_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MG_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Medic_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_CDF_Squad01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Soldier_GL_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Medic_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_AMG_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MG_MNT; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TWest; vehicle = CUP_B_CDF_Soldier_RPG18_MNT; rank = "PRIVATE"; position[] = {15,-15,0};};
				};
				class EfC_B_CDF_Squad02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_CDF;
					class Unit0 	{side = TWest; vehicle = CUP_B_CDF_Officer_MNT; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = CUP_B_CDF_Soldier_MNT; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = CUP_B_CDF_Medic_MNT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = CUP_B_CDF_Soldier_AAT_MNT; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = CUP_B_CDF_Soldier_AR_MNT; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TWest; vehicle = CUP_B_CDF_Soldier_LAT_MNT; rank = "PRIVATE"; position[] = {15,-15,0};};
				};
			};
		};
		class CUP_B_USMC
		{
			name = $STR_A3_CfgGroups_West_BLU_F0;
			class Infantry
			{
				class EfC_B_USMC_Team01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_USMC;
					class Unit0 	{side = TEast; vehicle = CUP_B_USMC_Soldier_TL; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TEast; vehicle = CUP_B_USMC_Soldier_AR; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TEast; vehicle = CUP_B_USMC_Soldier_LAT; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TEast; vehicle = CUP_B_USMC_Soldier; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfC_B_USMC_Team02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = CUP_B_USMC;
					class Unit0 	{side = TEast; vehicle = CUP_B_USMC_Soldier_GL; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TEast; vehicle = CUP_B_USMC_Soldier_AR; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TEast; vehicle = CUP_B_USMC_Soldier_Maskman; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TEast; vehicle = CUP_B_USMC_Soldier; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
			};
		};
	};
};

